# Generated by Django 2.2.3 on 2019-07-19 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190719_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='user/image/default.png', upload_to='users/image'),
        ),
    ]
