# Generated by Django 2.2.3 on 2019-07-20 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190719_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='users/image/default.png', upload_to='users/image'),
        ),
    ]
