# Generated by Django 2.2.3 on 2019-07-30 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190730_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, default='', null=True, upload_to='blog/video'),
        ),
    ]
