# Generated by Django 2.2.3 on 2019-07-30 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_follower'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follower',
        ),
    ]
