# Generated by Django 2.2.3 on 2019-08-14 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20190814_1659'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messege',
            old_name='user',
            new_name='messege_from',
        ),
        migrations.AddField(
            model_name='messege',
            name='messege_to',
            field=models.TextField(default=None),
        ),
    ]
